### ISSUE TITLE
SharePoint 2019 - SPInstallPrereqs : The prerequisite installer ran with the following unknown exit code 1620

### ISSUE THREAD

**Issue by Roness** [PowerShell/SharePointDsc#991]
#### "PowerShell DSC resource MSFT_SPInstallPrereqs  failed to execute Set-TargetResource functionality with error message: The prerequisite installer ran with the following unknown exit code 1620 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : PFE-APP-SP19"

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2019 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running
Name                           Value                                                                                        
----                           -----                                                                                        
PSVersion                      5.1.17763.1                                                                                  
PSEdition                      Desktop                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                      
BuildVersion                   10.0.17763.1                                                                                 
CLRVersion                     4.0.30319.42000                                                                              
WSManStackVersion              3.0                                                                                          
PSRemotingProtocolVersion      2.3                                                                                          
SerializationVersion           1.1.0.1

**Comment by ykuijs** [comment]
Error code 1620 means there is an issue with the MSI: http://www.msierrors.com/tag/msiexec-exit-code-1620/

What happens it you start the installer manually? Does it also give an error message?

**Comment by Roness** [comment]
If I try to install this file manually it work as well
i'm Still investigating this..

**Comment by ykuijs** [comment]
Can you share the verbose logging of DSC?

**Comment by Roness** [comment]
> Job {6D73C28B-F7B9-11E8-9117-00155D743F24} : 
Message The prerequisite installer ran with the following unknown exit code 1620 
HResult -2146233087 
StackTrack    at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.CoreInvokeRemoteHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.ResourceProviderAdapter.ExecuteCommand(PowerShell powerShell, ResourceModuleInfo resInfo, String operationCmd, List`1 acceptedProperties, CimInstance nonResourcePropeties, CimInstance resourceConfiguration, LCMDebugMode debugMode, PSInvocationSettings pSInvocationSettings, UInt32& resultStatusHandle, Collection`1& result, ErrorRecord& errorRecord, PSModuleInfo localRunSpaceModuleInfo)

> Job {6D73C28B-F7B9-11E8-9117-00155D743F24} : 
This event indicates that failure happens when LCM is processing the configuration. Error Id is 0x1. Error Detail is The SendConfigurationApply function did not succeed.. Resource Id is [SPInstallPrereqs]InstallPrerequisites and Source Info is C:\SharePoint\SharePointDSC_InstallPrereuisites.ps1::23::13::SPInstallPrereqs. Error Message is PowerShell DSC resource MSFT_SPInstallPrereqs  failed to execute Set-TargetResource functionality with error message: The prerequisite installer ran with the following unknown exit code 1620 .

> Job {6D73C28B-F7B9-11E8-9117-00155D743F24} : 
MIResult: 1
Error Message: PowerShell DSC resource MSFT_SPInstallPrereqs  failed to execute Set-TargetResource functionality with error message: The prerequisite installer ran with the following unknown exit code 1620 
Message ID: ProviderOperationExecutionFailure
Error Category: 7
Error Code: 1
Error Type: MI

**Comment by ykuijs** [comment]
Troubleshooted offline. The Software Requirements referred to the SP4 download for the SQL Native Client, with is a 1GB package (https://docs.microsoft.com/en-us/sharepoint/install/hardware-and-software-requirements-2019#software-requirements-for-sharepoint-server-2019). Unfortunately the PrerequisitesInstaller did not support this package and you need just the native client package: https://www.microsoft.com/en-us/download/details.aspx?id=50402

After using that package, the installation ran fine. @Roness Can you please validate and close the issue this solution worked?
